/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CreateStarRouteImport } from './routes/create-star'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EducatorsRouteImport } from './routes/educators'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HangarRouteImport } from './routes/hangar'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChaptersChapterIdRouteImport } from './routes/chapters.$chapterId'
import { Route as FriendsIndexRouteImport } from './routes/friends.index'
import { Route as FriendsFriendIdRouteImport } from './routes/friends.$friendId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnLessonRouteImport } from './routes/learn.$lesson'
import { Route as MissionsIndexRouteImport } from './routes/missions.index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PlayLevelRouteImport } from './routes/play.$level'
import { Route as StoryIndexRouteImport } from './routes/story.index'
import { Route as StoryChapterRouteImport } from './routes/story.$chapter'
import { Route as MissionsMissionIdIndexRouteImport } from './routes/missions.$missionId.index'
import { Route as MissionsMissionIdLevelIdRouteImport } from './routes/missions.$missionId.$levelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateStarRoute = CreateStarRouteImport.update({
  id: '/create-star',
  path: '/create-star',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EducatorsRoute = EducatorsRouteImport.update({
  id: '/educators',
  path: '/educators',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HangarRoute = HangarRouteImport.update({
  id: '/hangar',
  path: '/hangar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterIdRoute = ChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsIndexRoute = FriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsFriendIdRoute = FriendsFriendIdRouteImport.update({
  id: '/friends/$friendId',
  path: '/friends/$friendId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonRoute = LearnLessonRouteImport.update({
  id: '/learn/$lesson',
  path: '/learn/$lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIndexRoute = MissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLevelRoute = PlayLevelRouteImport.update({
  id: '/play/$level',
  path: '/play/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIndexRoute = StoryIndexRouteImport.update({
  id: '/story/',
  path: '/story/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryChapterRoute = StoryChapterRouteImport.update({
  id: '/story/$chapter',
  path: '/story/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsMissionIdIndexRoute = MissionsMissionIdIndexRouteImport.update({
  id: '/missions/$missionId/',
  path: '/missions/$missionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsMissionIdLevelIdRoute =
  MissionsMissionIdLevelIdRouteImport.update({
    id: '/missions/$missionId/$levelId',
    path: '/missions/$missionId/$levelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-star': typeof CreateStarRoute
  '/dashboard': typeof DashboardRoute
  '/educators': typeof EducatorsRoute
  '/explore': typeof ExploreRoute
  '/hangar': typeof HangarRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/settings': typeof SettingsRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/learn/$lesson': typeof LearnLessonRoute
  '/play/$level': typeof PlayLevelRoute
  '/story/$chapter': typeof StoryChapterRoute
  '/friends/': typeof FriendsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/play/': typeof PlayIndexRoute
  '/story/': typeof StoryIndexRoute
  '/missions/$missionId/$levelId': typeof MissionsMissionIdLevelIdRoute
  '/missions/$missionId/': typeof MissionsMissionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-star': typeof CreateStarRoute
  '/dashboard': typeof DashboardRoute
  '/educators': typeof EducatorsRoute
  '/explore': typeof ExploreRoute
  '/hangar': typeof HangarRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/settings': typeof SettingsRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/learn/$lesson': typeof LearnLessonRoute
  '/play/$level': typeof PlayLevelRoute
  '/story/$chapter': typeof StoryChapterRoute
  '/friends': typeof FriendsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/missions': typeof MissionsIndexRoute
  '/play': typeof PlayIndexRoute
  '/story': typeof StoryIndexRoute
  '/missions/$missionId/$levelId': typeof MissionsMissionIdLevelIdRoute
  '/missions/$missionId': typeof MissionsMissionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-star': typeof CreateStarRoute
  '/dashboard': typeof DashboardRoute
  '/educators': typeof EducatorsRoute
  '/explore': typeof ExploreRoute
  '/hangar': typeof HangarRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/settings': typeof SettingsRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/learn/$lesson': typeof LearnLessonRoute
  '/play/$level': typeof PlayLevelRoute
  '/story/$chapter': typeof StoryChapterRoute
  '/friends/': typeof FriendsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/play/': typeof PlayIndexRoute
  '/story/': typeof StoryIndexRoute
  '/missions/$missionId/$levelId': typeof MissionsMissionIdLevelIdRoute
  '/missions/$missionId/': typeof MissionsMissionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create-star'
    | '/dashboard'
    | '/educators'
    | '/explore'
    | '/hangar'
    | '/profile'
    | '/quiz'
    | '/settings'
    | '/chapters/$chapterId'
    | '/friends/$friendId'
    | '/learn/$lesson'
    | '/play/$level'
    | '/story/$chapter'
    | '/friends/'
    | '/learn/'
    | '/missions/'
    | '/play/'
    | '/story/'
    | '/missions/$missionId/$levelId'
    | '/missions/$missionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create-star'
    | '/dashboard'
    | '/educators'
    | '/explore'
    | '/hangar'
    | '/profile'
    | '/quiz'
    | '/settings'
    | '/chapters/$chapterId'
    | '/friends/$friendId'
    | '/learn/$lesson'
    | '/play/$level'
    | '/story/$chapter'
    | '/friends'
    | '/learn'
    | '/missions'
    | '/play'
    | '/story'
    | '/missions/$missionId/$levelId'
    | '/missions/$missionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/create-star'
    | '/dashboard'
    | '/educators'
    | '/explore'
    | '/hangar'
    | '/profile'
    | '/quiz'
    | '/settings'
    | '/chapters/$chapterId'
    | '/friends/$friendId'
    | '/learn/$lesson'
    | '/play/$level'
    | '/story/$chapter'
    | '/friends/'
    | '/learn/'
    | '/missions/'
    | '/play/'
    | '/story/'
    | '/missions/$missionId/$levelId'
    | '/missions/$missionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateStarRoute: typeof CreateStarRoute
  DashboardRoute: typeof DashboardRoute
  EducatorsRoute: typeof EducatorsRoute
  ExploreRoute: typeof ExploreRoute
  HangarRoute: typeof HangarRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  SettingsRoute: typeof SettingsRoute
  ChaptersChapterIdRoute: typeof ChaptersChapterIdRoute
  FriendsFriendIdRoute: typeof FriendsFriendIdRoute
  LearnLessonRoute: typeof LearnLessonRoute
  PlayLevelRoute: typeof PlayLevelRoute
  StoryChapterRoute: typeof StoryChapterRoute
  FriendsIndexRoute: typeof FriendsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  MissionsIndexRoute: typeof MissionsIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  StoryIndexRoute: typeof StoryIndexRoute
  MissionsMissionIdLevelIdRoute: typeof MissionsMissionIdLevelIdRoute
  MissionsMissionIdIndexRoute: typeof MissionsMissionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-star': {
      id: '/create-star'
      path: '/create-star'
      fullPath: '/create-star'
      preLoaderRoute: typeof CreateStarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educators': {
      id: '/educators'
      path: '/educators'
      fullPath: '/educators'
      preLoaderRoute: typeof EducatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangar': {
      id: '/hangar'
      path: '/hangar'
      fullPath: '/hangar'
      preLoaderRoute: typeof HangarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapterId': {
      id: '/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof ChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/': {
      id: '/friends/'
      path: '/friends'
      fullPath: '/friends/'
      preLoaderRoute: typeof FriendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/$friendId': {
      id: '/friends/$friendId'
      path: '/friends/$friendId'
      fullPath: '/friends/$friendId'
      preLoaderRoute: typeof FriendsFriendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lesson': {
      id: '/learn/$lesson'
      path: '/learn/$lesson'
      fullPath: '/learn/$lesson'
      preLoaderRoute: typeof LearnLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/': {
      id: '/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof MissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$level': {
      id: '/play/$level'
      path: '/play/$level'
      fullPath: '/play/$level'
      preLoaderRoute: typeof PlayLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/': {
      id: '/story/'
      path: '/story'
      fullPath: '/story/'
      preLoaderRoute: typeof StoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$chapter': {
      id: '/story/$chapter'
      path: '/story/$chapter'
      fullPath: '/story/$chapter'
      preLoaderRoute: typeof StoryChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$missionId/': {
      id: '/missions/$missionId/'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId/'
      preLoaderRoute: typeof MissionsMissionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$missionId/$levelId': {
      id: '/missions/$missionId/$levelId'
      path: '/missions/$missionId/$levelId'
      fullPath: '/missions/$missionId/$levelId'
      preLoaderRoute: typeof MissionsMissionIdLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateStarRoute: CreateStarRoute,
  DashboardRoute: DashboardRoute,
  EducatorsRoute: EducatorsRoute,
  ExploreRoute: ExploreRoute,
  HangarRoute: HangarRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  SettingsRoute: SettingsRoute,
  ChaptersChapterIdRoute: ChaptersChapterIdRoute,
  FriendsFriendIdRoute: FriendsFriendIdRoute,
  LearnLessonRoute: LearnLessonRoute,
  PlayLevelRoute: PlayLevelRoute,
  StoryChapterRoute: StoryChapterRoute,
  FriendsIndexRoute: FriendsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  MissionsIndexRoute: MissionsIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  StoryIndexRoute: StoryIndexRoute,
  MissionsMissionIdLevelIdRoute: MissionsMissionIdLevelIdRoute,
  MissionsMissionIdIndexRoute: MissionsMissionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
